name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: rm -rf playwright-report src/reporting/allure-results src/reporting/allure-report
      - run: docker build -t playwright-framework .
      
      # Run UI tests first
      - run: |
          docker run --rm \
            -e TEST_ENV=int \
            -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
            -v ${{ github.workspace }}/src/reporting/allure-results:/app/src/reporting/allure-results \
            -v ${{ github.workspace }}/src/reporting/allure-report:/app/src/reporting/allure-report \
            playwright-framework npx playwright test --project=ui

      # Run API tests after UI tests finish
      - run: |
          docker run --rm \
            -e TEST_ENV=int \
            -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
            -v ${{ github.workspace }}/src/reporting/allure-results:/app/src/reporting/allure-results \
            -v ${{ github.workspace }}/src/reporting/allure-report:/app/src/reporting/allure-report \
            playwright-framework npx playwright test --project=api

      # Upload reports steps remain same
